/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ljt_ndkdemos_utils_ViewUtils */

#ifndef _Included_com_ljt_ndkdemos_utils_ViewUtils
#define _Included_com_ljt_ndkdemos_utils_ViewUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ljt_ndkdemos_utils_ViewUtils
 * Method:    callMethod1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ljt_ndkdemos_utils_ViewUtils_callMethod1
  (JNIEnv *, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
