/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ljt_ndkdemos_utils_ViewUtils */

#ifndef _Included_com_ljt_ndkdemos_utils_ViewUtils
#define _Included_com_ljt_ndkdemos_utils_ViewUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ljt_ndkdemos_utils_ViewUtils
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ljt_ndkdemos_utils_ViewUtils_getStringFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
